# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7243107e0a8bc127c90d2baf2078bf5eba52f65cc91563872c13deeef845892585607e9413fa9bba26c97d0fb99a0df94adac0b23895d2926ca4e4222645a8fc

test:
  secret_key_base: 0fc3f12f48f43c6114b919d2286064662ae3b3417a5febbb9eb1be071cb585e504a277cc0abc633181745a829f88292afe2448b17e281cd714a9b8d78a4afe87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
 # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 2acf218ed005a542c779d3cfd4014a8679ddc2bf3832c22b41ee519c50833f7b9f233e983a448596322bb827370c0b49ec2d49802d952460d8f60ea344f2499e
